### ISSUE TITLE
Suggestion for rules

### ISSUE THREAD

**Issue by SiwMeckelborg** [difi/vefa-ehf-espd#1]
- [x] Date and time must not include timezone information
-- Date format = YYYY-MM-DD
-- Time format = hh:mm:ss
- [X] Code list for EndpointID/schemeID or fixed value NO:ORGNR?
- [X] Valid codes for espd-cac:EconomicOperatorParty/cac:Party/PartyIdentification/cbc:ID/@schemeID are VAT_Number or National_Number, should we mandate use of National_Number, and verify the corresponding ID element is a valid org.nr?
- [X] Validate UUIDs from Criteria Taxonomy (Criterion ids  and requirement ids) and add as code list
- [X] Validate Criterion name and description, and add as a code list
- [X] Validate correct combination of Requirement/@ResponseTypeCode and Response-element.
-- Example: If @ResponseTypeCode ="AMOUNT", Response/cbc:Amount must be present.
- [x] validate correct use of unitCode for Response/Quantity, according to ResponseDataType
- [x] Add code list for unitCode, and validate values

**Comment by klakegg** [comment]
* Date and time must not include timezone information
  * Date format = YYYY-MM-DD
  * Time format = hh:mm:ss

Realized as EHF-ESPD-R020 and EHF-ESPD-R021.

* Code list for EndpointID/schemeID or fixed value NO:ORGNR?

Code list supported for completeness, fixed value "NO:ORGNR" expected. Validation of organization number.

* Valid codes for espd-cac:EconomicOperatorParty/cac:Party/PartyIdentification/cbc:ID/@schemeid are VAT_Number or National_Number, should we mandate use of National_Number, and verify the corresponding ID element is a valid org.nr?

Fixed value 'National_Number'. Validation of organization number.

* Validate UUIDs from Criteria Taxonomy (Criterion ids and requirement ids) and add as code list

Part of validation related to criteria taxonomy. Not added as separate code list.

* Validate Criterion name and description, and add as a code list

Part of validation related to criteria taxonomy. Not added as separate code list.

* Validate correct combination of Requirement/@responsetypecode and Response-element.
-- Example: If @responsetypecode ="AMOUNT", Response/cbc:Amount must be present.

Realized as EHF-ESPD-R020 -> EHS-ESPD-R031.
