### ISSUE TITLE
ESPD 1.1 validation issue

### ISSUE THREAD

**Issue by b75nguyen** [difi/vefa-ehf-espd#3]
We are testing ESPD 1.1 using this test site from Difi https://vefa.difi.no/validator/

The file we tested is generated from this json
https://github.com/ESPD/ESPD-Service/blob/master/espd-web/src/main/resources/criteria/exclusionCriteria.json 

There is a mismatch between xml created from above Json file and the EHF ESPD 1.1 validation from Difi

Test file is here:
[ESPD Request from Mercell error when validated.zip](https://github.com/difi/vefa-ehf-espd/files/2915126/ESPD.Request.from.Mercell.error.when.validated.zip)

**Comment by klakegg** [comment]
The ESPD Service is not normative for EHF ESPD 1.x. Please see the taxonomy provided by EHF ESPD 1.x.
